# Site settings
title: Thiago Tomasi - Product Design & Front-end Development
author: Thiago Tomasi
author_title: Product Design & Front-end Development
email: alpaca.thiago@gmail.com
baseurl: ""
url: "https://www.thiagotomasi.com/"
twitter_username:  thiagotomasi
github_username:   thiagotomasi
facebook_username: thiagotomasi
medium_username:   thiagotomasi
linkedin_username: thiagotomasi
instagram_username: thiago.tomasi

# Build settings
markdown: kramdown

exclude: [
  "gulpfile.js",
  "node_modules",
  "package.json"
]